services:
  mysql:
    image: mysql:8.4
    container_name: zahuu-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: zahuu_chat
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-proot123']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: zahuu-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
  mailpit:
    image: axllent/mailpit:latest
    container_name: zahuu-mailpit
    restart: unless-stopped
    ports:
      - '1025:1025'
      - '8025:8025'

volumes:
  mysql_data:
  redis_data:
